### PR TITLE
New RQL Format Proposal

### PR DESCRIPTION
**Pull request by csestito**
## Description

Added React Tables implementation to allow for search and better view of RQL queries

## Motivation and Context

To Provide a better DX for RQL queries

## How Has This Been Tested?

This is a working example of all AWS RQLs, will add others if approved.

## Types of changes

New Feature

## Checklist

- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by csestito** [comment]
#44 @solalraveh

**Comment by solalraveh** [comment]
@csestito I see this after 'yarn start' and the web page loading:
image

**Comment by solalraveh** [comment]
I'm not the day to day React person for you, but I think that the react-table dependency should also be in the directory structure, but I can't find it, unless if I'm missing something and need to install:
image

Also did npm install react-table (both versions 6 and 7) but no dice. Anything I need to do to try it out?..

**Comment by solalraveh** [comment]
Legend! Both dark mode and new RQL views look very good!

**Comment by csestito** [comment]
Reopening this in a new commit later this week

**Pull request closed without merging**
