### PR TITLE
a lotta new RQL examples

### PR DESCRIPTION
**Pull request by solalraveh**
## Description

across the services. more to come, out of time today.
New files: ACR, ECR, RDS, VPC, Azure Storage, AKS, ALB, App Svc, Cosmos, SQL DB. 
Modified Azure VM

## Motivation and Context

More RQLs examples. More to come.

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ x ] I have updated the documentation accordingly.
- [ x ] I have read the **CONTRIBUTING** document.
- [ x ] I have added tests to cover my changes if appropriate.
- [ x ] All new and existing tests passed.

### CODE REVIEW

**Comment by solalraveh** [comment]
Hey Eddie, that description you mentioned makes sense to the query in question. So that specific example means if a summary exists, then there are vulns found on that ECR.
FYI, I've also put a "note" to a bunch of queries, so the logic is explained instead of just a query name..

And yes, other appear to be good too.
Thanks for properly checking man! good to know if something is missed / misspelled etc.

**Review by ebeuerle — COMMENTED** [review]
config from cloud.resource where api.name = 'aws-ecr-image' AND json.rule = imageScanFindingsSummary does not exist 

this will alert if imageScanFindingsSummary doesn't exist - which would show images that DON'T have vulns right?  I think it should be: exists.  Am I missing something?

**Comment by solalraveh** [comment]
Like I said earlier, super thanks for catching snafu’s like this. Yes, should be exists. 
I’ll reverse the check later and send another commit.

**Review by ebeuerle — APPROVED** [review]
Looks good.

**Pull request merged**
